const MOOD_OPTIONS = [
  // 🎵 Music Styles
  { value: "lo-fi", label: "🎧 Lo-Fi Chill" },
  { value: "upbeat", label: "⚡ Upbeat & Energetic" },
  { value: "ambient", label: "🌊 Ambient & Atmospheric" },
  { value: "jazz", label: "🎷 Smooth Jazz" },
  { value: "cinematic", label: "🎬 Cinematic & Epic" },
  { value: "acoustic", label: "🎸 Acoustic & Warm" },
  { value: "electronic", label: "🤖 Electronic & Modern" },
  { value: "hiphop", label: "🎤 Hip-Hop / Trap" },
  { value: "gospel", label: "✝️ Gospel / Inspirational" },
  { value: "afrobeats", label: "🌍 African / Afrobeats" },
  { value: "rnb", label: "🎶 R&B / Soul" },
  { value: "reggae", label: "🌴 Reggae / Chill Vibes" },
  { value: "classical", label: "🎻 Classical / Orchestra" },
  { value: "country", label: "🤠 Country / Folk" },
  { value: "latin", label: "💃 Latin / Salsa" },
  // 📻 Show Styles
  { value: "news", label: "📰 News Broadcast" },
  { value: "morning_drive", label: "🌅 Morning Drive Radio" },
  { value: "comedy", label: "😂 Comedy / Funny Show" },
  { value: "true_crime", label: "🔍 True Crime / Mystery" },
  { value: "tech", label: "💻 Tech / Startup" },
  { value: "sports", label: "🏆 Sports Commentary" },
  { value: "war", label: "⚔️ War / Military Drama" },
  { value: "documentary", label: "🎥 Documentary" },
  { value: "talk_show", label: "🎙️ Late Night Talk Show" },
  { value: "business", label: "💼 Business & Finance" },
  { value: "spiritual", label: "🙏 Spiritual / Meditation" },
  { value: "horror", label: "👻 Horror / Suspense" },
  { value: "kids", label: "🧸 Kids / Family Fun" },
  { value: "romance", label: "❤️ Romance / Drama" },
  { value: "science", label: "🔬 Science & Discovery" },
];
